version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

# we can run directly in IDE
#Commands :
#docker compose -f kafka-docker.yml up -d
#docker exec -it kafka /bin/sh
# cd opt/kafka_2.13-2.8.1/bin
#  kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic kumartopic

#Produce/consume messages
#kafka-console-producer.sh --topic kumartopic --bootstrap-server localhost:9092
#kafka-console-consumer.sh --topic kumartopic --bootstrap-server localhost:9092